# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

term xterm-kitty
font_family Fira Code
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto
shell /bin/bash
background_opacity 0.95
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1
# kitty_mod = ctrl+shift
map kitty_mod+up    scroll_line_up       # Ctrl+Shift+↑ sube 1 línea
map kitty_mod+down  scroll_line_down     # Ctrl+Shift+↓ baja 1 línea
map kitty_mod+shift+up    scroll_page_up   # Ctrl+Shift+Shift+↑ = página arriba
map kitty_mod+shift+down  scroll_page_down # Ctrl+Shift+Shift+↓ = página abajo
allow_graphics yes

# OS specific tweaks
include os/${KITTY_OS}.conf

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4
window_border_width 1
hide_window_decorations yes
# selection_foreground none
# selection_background none
# foreground #dddddd
# background #000000
# cursor #dddddd

#Behavior
allow_remote_control yes
enabled_layouts grid
startup_session ~/.config/kitty/session.conf

# BEGIN_KITTY_THEME
# Default
include current-theme.conf
include ${HOME}/.config/kitty-local/theme.conf
# END_KITTY_THEME
