background            #2a2c2e
foreground            #dadada
cursor                #fcee0b
selection_background  #2a2c2e
color0                #1b1d1e
color8                #fffdd0
color1                #550604
color9                #999900
color2                #c8be46
color10               #fff27c
color3                #550604
color11               #feed6c
color4                #100c08 
color12               #909495
color5                #fffafa
color13               #9a999d
color6                #a9a9a9
color14               #fad6a5
color7                #c5c5be
color15               #dadad5
selection_foreground #1b1d1e
