background            #000000
foreground            #e9e9e9
cursor                #e9e9e9
selection_background  #000000
color0                #fdf6e3
color8                #6c6c6c
color1                #d44d53
color9                #d44d53
color2                #f75f5f
color10               #b9c949
color3                #e6c446
color11               #e6c446
color4                #5f87ff
color12               #79a6da
color5                #c678dd
color13               #c396d7
color6                #56b6c2
color14               #70c0b1
color7                #fffefe
color15               #fffefe
selection_foreground #000000
