
#Gestión de inactividad y suspension del equipo

general {
   lock_cmd = pidof hyprlock || hyprlock
   before_sleep_cmd = loginctl lock-session
   after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on && brightnessctl -r
}

#Bajar brillo tras 5 mins sin actividad
listener {
   timeout = 300
   on-timeout = brightnessctl -s set 15
   on-resume = brightnessctl -r
} 



# Apagar pantalla tras 7.5 min
listener {
    timeout = 450
    on-timeout = hyprctl dispatch dpms off
    on-resume = brightnessctl -r
}

# Bloquear sesión tras 10 min
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Suspender tras 12.5 min
listener {
    timeout = 750
    on-timeout = systemctl suspend
}


































































