#Configuración de la pantalla de bloqueo



general {
 
   immediate_render = true

}

background{

   monitor = *  
   path = ~/Images_Icons/WALL.png
   color = rgba(25, 20, 20, 1.0)
   blur_passes = 0
   blur_size = 15

}

input-field{

   monitor = *
   size = 250, 40 
   outline_thickness = 1
   outer_color = rgba(200,200,200,0.7)
   inner_color = rgba(255,255,255, 0.5)
   font_color = rgba (255,255,255, 0.8)

   dots_size = 0.3
   dots_spacing = 0.55
   dots_center = true
   dots_rounding = -1

   fade_on_empty = false
   hide_input = false

   placeholder_text = Enter your password
   check_color = rgba(204, 136, 34, 0.4)
   fail_color = rgba(204, 34, 34, 0.5)

   position = 0,0
   halign = center
   valign = center
 

}

label {

   monitor = *
   text = cmd[update:1000] echo "$(date '+%A %d %B')"
   color = rgba(240,240,240,0.9)
   font_size = 20
   position = 0, 260
   halign = center
   valign = center
}

label {

   monitor = *
   text = cmd[update:1000] echo "$(date '+%H:%M')"
   color = rgba(240, 240, 240, 0.9)
   font_size = 70
   position = 0, 200
   halign = center
   valign = center

}
