# Scripts, comands or things related that are going to be excuted at the beginning

exec-once = hypridle
exec-once = hyprlock
exec-once = swww-daemon
# exec-once = kanshi
exec-once = ~/.config/hypr/scripts/use-laptop.sh
exec-once = ~/.config/hypr/scripts/move-workspaces-external.sh
exec-once = ~/.config/hypr/scripts/monitor-listener.sh
exec-once = sudo keyd
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.round.css
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = ~/.config/hypr/scripts/start-polkit-agent.sh


exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = /usr/libexec/xdg-desktop-portal &
exec-once = /usr/lib/flatpak/flatpak-session-helper &















































