#Opacity
windowrulev2 = opacity 0.99999 override, class:^(zen)$
windowrulev2 = opacity 0.95 0.95, class:^(Spotify)$
windowrulev2 = opacity 0.95 0.95, class:^(kitty)$
windowrulev2 = opacity 0.95 0.95, class:^(rofi)$
windowrulev2 = opacity 0.95 0.95, class:^(Code)$
windowrulev2 = opacity 0.95 0.95, class:^(obsidian)$
windowrulev2 = opacity 0.95 0.95, class:^(net.ankiweb.Anki)$
windowrulev2 = opacity 0.95 0.95, class:^(com.rtosta.zapzap)$
windowrulev2 = opacity 0.95 0.95, class:^(thunar)$
windowrulev2 = opacity 0.95 0.95, class:^(pbe.QQwnNotes)

#Workspace
windowrulev2 = workspace 1, class:^(zen)$
windowrulev2 = workspace 2, class:^(Code)$
windowrulev2 = workspace 3, class:^(Spotify)$
windowrulev2 = workspace 4, class:^(obsidian)$
windowrulev2 = workspace 4, class:^(net.ankiweb.Anki)$
windowrulev2 = workspace 4, class:^(PBE.QOwnNotes)$
windowrulev2 = workspace 3, class:^(com.rtosta.zapzap)$


#Position
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = move 72.7% 61%, class:^(org.pulseaudio.pavucontrol)
windowrulev2 = float,class:^(notification)$
windowrulev2 = move 72.7% 61%, class:^(notification)
#Size
windowrulev2 = size 800 600,class:^(download)$
windowrulev2 = size 800 600,title:^(Open File)$
windowrulev2 = size 800 600,title:^(Save File)$
windowrulev2 = size 800 600,title:^(org.pulseaudio.pavucontrol)$
